name: Lint

on:
  push:
    paths:
      - 'notion_mirror'
      - 'tests'
      - '*.py'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --system --deploy --dev

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_args: " --check notion_mirror tests *.py"
          flake8: true
          flake8_args: "notion_mirror tests *.py"
          mypy: true
          mypy_args: "--ignore-missing-imports notion_mirror *.py"
